[package]
name = "mdbook-code-preprocessor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.4"
mdbook = "0.4.28"
regex = "1.8.1"
semver = "1.0.17"
serde_json = "1.0.96"
